version: '3.8'

services:

  backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/app
        target: /code/app
    # ports:
    #   - "8000:8000"
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  caddy-data:
  caddy-config:
